### ISSUE TITLE
About crate name

### ISSUE THREAD

**Issue by hlhr202** [shadowmint/llama-rs#1]
if i attempt to port your binding to nodejs but still keep original llama-rs crate in pure rust. how should i solve package naming conflict.

would it be better if you rename this to llama-binding or something else to clarify its a different libs compared to llama-rs?

**Comment by shadowmint** [comment]
yeah, I was stumbling into this myself today trying to use the *actual* llama-rs and this crate at the same time.

I may rename these crates `llama-cpp-sys` and `llama-cpp-rs` because they're really bindings of `llama.cpp`, not really llama itself.

I just picked it because `llama.cpp` generates `libllama` and the standard naming for `libfoo` is `foo-sys` and `foo-rs`... but it's a bit annoying.

I'll try to get some time to do a rename tomorrow.

**Comment by shadowmint** [comment]
https://github.com/shadowmint/llama-cpp-rs/commit/f232d7769a809f89a77c64e95a60f690eeb2c96c renames the crate and the underlying -sys crate resolving this unambiguously now.
